// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {autoupdater} from '../models';
import {main} from '../models';

export function CheckForUpdates():Promise<autoupdater.UpdateInfo>;

export function DeleteGenerator(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function InstallUpdate(arg1:string):Promise<void>;

export function ListGenerators():Promise<Array<main.GeneratorInfo>>;

export function LoadGenerator(arg1:string):Promise<string>;

export function LoadGeneratorConfig(arg1:string):Promise<string>;

export function SaveGenerator(arg1:string,arg2:string):Promise<void>;

export function SaveGeneratorConfig(arg1:string,arg2:string):Promise<void>;
