// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGenerator(arg1) {
  return window['go']['main']['App']['DeleteGenerator'](arg1);
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function ListGenerators() {
  return window['go']['main']['App']['ListGenerators']();
}

export function LoadGenerator(arg1) {
  return window['go']['main']['App']['LoadGenerator'](arg1);
}

export function LoadGeneratorConfig(arg1) {
  return window['go']['main']['App']['LoadGeneratorConfig'](arg1);
}

export function SaveGenerator(arg1, arg2) {
  return window['go']['main']['App']['SaveGenerator'](arg1, arg2);
}

export function SaveGeneratorConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGeneratorConfig'](arg1, arg2);
}
