// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ConvertVideoToMP4(arg1, arg2) {
  return window['go']['main']['App']['ConvertVideoToMP4'](arg1, arg2);
}

export function DeleteGenerator(arg1) {
  return window['go']['main']['App']['DeleteGenerator'](arg1);
}

export function DeleteTempFile(arg1) {
  return window['go']['main']['App']['DeleteTempFile'](arg1);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetLastSeenVersion() {
  return window['go']['main']['App']['GetLastSeenVersion']();
}

export function GetLatestReleaseInfo() {
  return window['go']['main']['App']['GetLatestReleaseInfo']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function InstallUpdateWithRestart(arg1) {
  return window['go']['main']['App']['InstallUpdateWithRestart'](arg1);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function IsFFmpegInstalled() {
  return window['go']['main']['App']['IsFFmpegInstalled']();
}

export function IsFirstRunAfterUpdate() {
  return window['go']['main']['App']['IsFirstRunAfterUpdate']();
}

export function IsFirstTimeUser() {
  return window['go']['main']['App']['IsFirstTimeUser']();
}

export function ListGenerators() {
  return window['go']['main']['App']['ListGenerators']();
}

export function LoadGenerator(arg1) {
  return window['go']['main']['App']['LoadGenerator'](arg1);
}

export function LoadGeneratorConfig(arg1) {
  return window['go']['main']['App']['LoadGeneratorConfig'](arg1);
}

export function MarkVersionAsSeen() {
  return window['go']['main']['App']['MarkVersionAsSeen']();
}

export function ReadTempFile(arg1) {
  return window['go']['main']['App']['ReadTempFile'](arg1);
}

export function SaveGenerator(arg1, arg2) {
  return window['go']['main']['App']['SaveGenerator'](arg1, arg2);
}

export function SaveGeneratorConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGeneratorConfig'](arg1, arg2);
}

export function SaveTempFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTempFile'](arg1, arg2);
}

export function SetLastSeenVersion(arg1) {
  return window['go']['main']['App']['SetLastSeenVersion'](arg1);
}

export function ShouldShowChangelog() {
  return window['go']['main']['App']['ShouldShowChangelog']();
}
