name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: windows-latest
            name: windows
            extension: .exe
            arch: amd64
          - os: ubuntu-22.04
            name: linux
            extension: ""
            arch: amd64
          - os: macos-latest
            name: darwin
            extension: ""
            arch: amd64

    runs-on: ${{ matrix.platform.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install Linux dependencies
        if: matrix.platform.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build Windows app
        if: matrix.platform.os == 'windows-latest'
        run: |
          wails build -platform windows/amd64 -ldflags "-w -s"
        
      - name: Build Linux app
        if: matrix.platform.os == 'ubuntu-22.04'
        run: |
          wails build -platform linux/amd64 -ldflags "-w -s"

      - name: Build macOS app
        if: matrix.platform.os == 'macos-latest'
        run: |
          wails build -platform darwin/amd64 -ldflags "-w -s"

      - name: Package Windows app
        if: matrix.platform.os == 'windows-latest'
        run: |
          New-Item -ItemType Directory -Force -Path release
          Compress-Archive -Path build/bin/VibeCraft.exe -DestinationPath release/VibeCraft-${{ matrix.platform.name }}-${{ matrix.platform.arch }}.zip

      - name: Package Linux app
        if: matrix.platform.os == 'ubuntu-22.04'
        run: |
          mkdir -p release
          cd build/bin
          tar -czf ../../release/VibeCraft-${{ matrix.platform.name }}-${{ matrix.platform.arch }}.tar.gz VibeCraft

      - name: Package macOS app
        if: matrix.platform.os == 'macos-latest'
        run: |
          mkdir -p release
          cd build/bin
          tar -czf ../../release/VibeCraft-${{ matrix.platform.name }}-${{ matrix.platform.arch }}.tar.gz VibeCraft.app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeCraft-${{ matrix.platform.name }}-${{ matrix.platform.arch }}
          path: release/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/VibeCraft-windows-amd64/*
            artifacts/VibeCraft-linux-amd64/*
            artifacts/VibeCraft-darwin-amd64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 